require("config.options")
require("config.keymaps")
require("config.lazy")
require("config.cmds")
vim.cmd.colorscheme("gruber-darker")
vim.api.nvim_set_hl(0, "MiniPickMatchCurrent", { link = "Visual" })
