require("config.options")
require("config.keymaps")
require("config.lazy")
require("config.cmds")
vim.cmd.colorscheme("oh-lucy") -- gruber-darker, no-clown-fiesta, vscode, oxocarbon, poimandres, mellow, oh-lucy(-evening)
