vim.keymap.set("v", "<", "<gv", { desc = "dedent" })
vim.keymap.set("v", ">", ">gv", { desc = "indent" })
vim.keymap.set("n", "<TAB>", ":bn<CR>", { desc = "next tab" })
vim.keymap.set("n", "<S-TAB>", ":bp<CR>", { desc = "previous tab" })
vim.keymap.set("n", "n", "nzzzv", { desc = "next match and center" })
vim.keymap.set("n", "N", "Nzzzv", { desc = "previous match and center" })
vim.keymap.set("n", "<c-h>", "<c-w><c-h>", { desc = "Move focus to the left window" })
vim.keymap.set("n", "<c-l>", "<c-w><c-l>", { desc = "Move focus to the right window" })
vim.keymap.set("n", "<c-j>", "<c-w><c-j>", { desc = "Move focus to the lower window" })
vim.keymap.set("n", "<c-k>", "<c-w><c-k>", { desc = "Move focus to the upper window" })
vim.keymap.set("n", "<C-Up>", ":resize -2<CR>", { desc = "resize up" })
vim.keymap.set("n", "<C-Down>", ":resize +2<CR>", { desc = "resize down" })
vim.keymap.set("n", "<C-Left>", ":vertical resize -2<CR>", { desc = "resize left" })
vim.keymap.set("n", "<C-Right>", ":vertical resize +2<CR>", { desc = "resize right" })
vim.keymap.set("n", "<C-d>", "<C-d>zz", { desc = "next page and center" })
vim.keymap.set("n", "<C-u>", "<C-u>zz", { desc = "previous page and center" })
vim.keymap.set("n", "<A-j>", ":m .+1<CR>==", { desc = "move line up" })
vim.keymap.set("n", "<A-k>", ":m .-2<CR>==", { desc = "move line down" })
vim.keymap.set("i", "<A-j>", "<Esc>:m .+1<CR>==gi", { desc = "move line up" })
vim.keymap.set("i", "<A-k>", "<Esc>:m .-2<CR>==gi", { desc = "move line down" })
vim.keymap.set("i", "<A-u>", "<c-r>=trim(system('uuidgen'))<cr>", { desc = "insert uuid at cursor" })
vim.keymap.set("n", "<A-u>", "i<c-r>=trim(system('uuidgen'))<cr><esc>", { desc = "insert uuid at cursor" })
