local map = require("config.utils").map
map("v", "<", "<gv", "dedent")
map("v", ">", ">gv", "indent")
map("n", "n", "nzzzv", "center next match")
map("n", "N", "Nzzzv", "center previous match")
map("n", "<c-h>", "<c-w><c-h>", "focus left window")
map("n", "<c-l>", "<c-w><c-l>", "focus right window")
map("n", "<c-j>", "<c-w><c-j>", "focus lower window")
map("n", "<c-k>", "<c-w><c-k>", "focus upper window")
map("n", "<C-Up>", ":resize -2<CR>", "resize up")
map("n", "<C-Down>", ":resize +2<CR>", "resize down")
map("n", "<C-Left>", ":vertical resize -2<CR>", "resize left")
map("n", "<C-Right>", ":vertical resize +2<CR>", "resize right")
map("n", "<C-d>", "<C-d>zz", "center next page")
map("n", "<C-u>", "<C-u>zz", "center previous page")
map("i", "<A-u>", "<c-r>=trim(system('uuidgen'))<cr>", "uuid")
map("n", "<A-u>", "i<c-r>=trim(system('uuidgen'))<cr><esc>", "uuid")

map("n", "<leader>fe", ":Pick explorer<cr>", "file explorer")
map("n", "<leader>ff", ":Pick files<cr>", "find files")
map("n", "<leader>fh", ":Pick help<cr>", "find helptag")
map("n", "<leader>fb", ":Pick buffers<cr>", "find buffer")
map("n", "<leader>fg", ":Pick grep_live<cr>", "find pattern")
map("n", "<leader>fk", ":Pick keymaps<cr>", "find keymap")
map("n", "<leader>fm", ":Pick marks<cr>", "find marks")
map("n", "<leader>fr", ":Pick resume<cr>", "resume search")
map("n", "<leader>fR", ":Pick registers<cr>", "find register")
map("n", "<leader>xx", ":Pick diagnostic<cr>", "find keymap")
map("n", "-", ":lua require('mini.files').open()<cr>", "open files")
