local map = vim.keymap.set
map("v", "<", "<gv")
map("v", ">", ">gv")
map("i", "<A-u>", "<c-r>=trim(system('uuidgen'))<cr>")
map("n", "<A-u>", "i<c-r>=trim(system('uuidgen'))<cr><esc>")
map("n", "K", vim.lsp.buf.hover)
map("n", "<leader>k", vim.diagnostic.open_float)
map("i", "<C-b>", "<ESC>^i")
map("i", "<C-e>", "<End>")
map("n", "<Esc>", "<cmd>noh<CR>")
map({ "i", "x", "n", "s" }, "<C-s>", "<cmd>w<cr><esc>")
map("n", "-", ":Oil<cr>")
map("n", "<leader>ff", ":FzfLua files<cr>")
map("n", "<leader>fg", ":FzfLua live_grep_native<cr>")
map("n", "<leader>fb", ":FzfLua buffers<cr>")
map("n", "<leader>fr", ":FzfLua resume<cr>")
map("n", "<leader>/", ":FzfLua grep_curbuf<cr>")
map("n", "<leader>xx", ":FzfLua diagnostics_document<cr>")
map("n", "gca", ":FzfLua lsp_code_actions<cr>", { silent = true })
map("n", "grr", ":FzfLua lsp_references<cr>", { silent = true })
map("n", "gd", ":FzfLua lsp_definitions<cr>", { silent = true })
map("n", "gri", ":FzfLua lsp_implementations<cr>", { silent = true })
map("n", "grt", ":FzfLua lsp_typedefs<cr>", { silent = true })
map("n", "gO", ":FzfLua lsp_document_symbols<cr>", { silent = true })
