local g = vim.g
local opt = vim.opt
g.mapleader = " "
g.maplocalleader = ";"
opt.background = "dark"
opt.backupcopy = "yes"
opt.breakindent = true
opt.clipboard:append("unnamedplus")
opt.completeopt = { "menuone", "popup", "noselect", "noinsert" }
opt.confirm = true
opt.copyindent = true
opt.cursorline = true
opt.expandtab = true
opt.ignorecase = true
opt.infercase = true
opt.iskeyword:append("-")
opt.laststatus = 3
opt.number = true
opt.numberwidth = 4
opt.preserveindent = true
opt.pumheight = 10
opt.scrolloff = 5
opt.shiftround = true
opt.shiftwidth = 2
opt.showmode = false
opt.sidescrolloff = 5
opt.signcolumn = "yes"
opt.smartcase = true
opt.smartindent = true
opt.splitbelow = true
opt.splitright = true
opt.tabstop = 2
opt.termguicolors = true
opt.virtualedit = "block"
opt.wrap = false
