local opt = vim.opt
opt.background = "dark"
opt.backupcopy = "yes"
opt.breakindent = true
opt.breakindentopt = "list:-1"
opt.clipboard:append("unnamedplus")
opt.cmdwinheight = 30
opt.colorcolumn = "+0"
opt.completeopt = { "menu", "menuone", "noselect" }
opt.cursorline = true
opt.cursorlineopt = { "number" }
opt.diffopt = { "filler", "indent-heuristic", "linematch:60", "vertical" }
opt.equalalways = true
opt.expandtab = true
opt.hlsearch = true
opt.ignorecase = true
opt.inccommand = "split"
opt.infercase = true
opt.laststatus = 3
opt.modeline = false
opt.modelines = 0
opt.number = true
opt.numberwidth = 3
opt.preserveindent = true
opt.pumheight = 15
opt.redrawtime = 150
opt.ruler = false
opt.shiftround = true
opt.shiftwidth = 0
opt.shortmess = "acstFOSW"
opt.showtabline = 2
opt.signcolumn = "yes:1"
opt.smartcase = true
opt.smartindent = true
opt.softtabstop = -1
opt.splitbelow = true
opt.splitkeep = "screen"
opt.splitright = true
opt.tabstop = 2
opt.termguicolors = true
opt.title = true
opt.titlestring = "nvim: %t"
opt.undofile = true
opt.wildignore = "*.o"
opt.wildmode = "longest:full"
opt.wildoptions = "pum"
opt.winborder = "solid"
opt.wrap = false
opt.writebackup = false
