local g = vim.g
local opt = vim.opt
g.mapleader = " "
g.maplocalleader = ";"
opt.foldmethod = "expr"
opt.foldexpr = "v:lua.vim.lsp.foldexpr()"
opt.backupcopy = "yes"
opt.breakindent = true
opt.clipboard = "unnamedplus"
opt.confirm = true
opt.copyindent = true
opt.cursorline = true
opt.expandtab = true
opt.ignorecase = true
opt.infercase = true
opt.laststatus = 3
opt.number = true
opt.numberwidth = 4
opt.preserveindent = true
opt.pumheight = 10
opt.scrolloff = 5
opt.shiftround = true
opt.shiftwidth = 2
opt.sidescrolloff = 5
opt.signcolumn = "yes"
opt.smartcase = true
opt.smartindent = true
opt.splitbelow = true
opt.splitright = true
opt.tabstop = 2
opt.termguicolors = true
opt.virtualedit = "block"
opt.wrap = false
