-- return {
-- 	"nvim-neotest/neotest",
-- 	dependencies = {
-- 		"nvim-neotest/nvim-nio",
-- 		"nvim-lua/plenary.nvim",
-- 		"antoinemadec/FixCursorHold.nvim",
-- 		"nvim-treesitter/nvim-treesitter",
-- 		"nvim-neotest/neotest-go",
-- 	},
-- 	config = function()
-- 		local neotest_ns = vim.api.nvim_create_namespace("neotest")
-- 		vim.diagnostic.config({
-- 			virtual_text = {
-- 				format = function(diagnostic)
-- 					local msg = diagnostic.message:gsub("\n", " "):gsub("\t", " "):gsub("%s+", " "):gsub("^%s+", "")
-- 					return msg
-- 				end,
-- 			},
-- 		}, neotest_ns)
-- 		require("neotest").setup({
-- 			adapters = { require("neotest-go") },
-- 		})
-- 	end,
-- }
