return {
	{ "nyoom-engineering/oxocarbon.nvim", lazy = true, priority = 1000 },
	{
		"olivercederborg/poimandres.nvim",
		lazy = true,
		priority = 1000,
		opts = {
			bold_vert_split = true,
			dim_nc_background = true,
			disable_background = false,
			disable_float_background = false,
			disable_italics = true,
		},
	},
	{ "kvrohit/substrata.nvim", lazy = true, priority = 1000 },
	{
		"datsfilipe/vesper.nvim",
		lazy = true,
		priority = 1000,
		opts = {
			transparent = false,
			italics = {
				comments = false,
				keywords = false,
				functions = false,
				strings = false,
				variables = false,
			},
		},
	},
	{
		"no-clown-fiesta/no-clown-fiesta.nvim",
		lazy = true,
		priority = 1000,
		opts = {
			transparent = false,
			styles = {
				comments = {},
				functions = { bold = true },
				keywords = { bold = true },
				lsp = { underline = true },
				match_paren = {},
				type = { bold = true },
				variables = {},
			},
		},
	},
	{ "cocopon/iceberg.vim", lazy = true, priority = 1000 },
	{
		"olimorris/onedarkpro.nvim",
		lazy = true,
		priority = 1000,
		opts = {
			styles = {
				types = "bold",
				methods = "bold",
				numbers = "NONE",
				strings = "NONE",
				comments = "NONE",
				keywords = "bold",
				constants = "bold",
				functions = "bold",
				operators = "NONE",
				variables = "NONE",
				parameters = "NONE",
				conditionals = "NONE",
				virtual_text = "NONE",
			},
			filetypes = {
				c = true,
				comment = true,
				go = true,
				html = true,
				java = true,
				javascript = true,
				json = true,
				lua = true,
				markdown = true,
				php = true,
				python = true,
				ruby = true,
				rust = true,
				scss = true,
				toml = true,
				typescript = true,
				typescriptreact = true,
				vue = true,
				xml = true,
				yaml = true,
			},
			plugins = {
				gitsigns = true,
				nvim_cmp = true,
				nvim_hlslens = true,
				nvim_lsp = true,
				nvim_notify = true,
				nvim_ts_rainbow = true,
				telescope = true,
				toggleterm = true,
				treesitter = true,
				trouble = true,
				which_key = true,
			},
			options = {
				cursorline = true,
				transparency = false,
				terminal_colors = true,
				lualine_transparency = false,
				highlight_inactive_windows = false,
			},
		},
	},
	{ "dasupradyumna/midnight.nvim", lazy = true, priority = 1000 },
	{
		"miikanissi/modus-themes.nvim",
		lazy = true,
		priority = 1000,
		config = function()
			require("modus-themes").setup({
				style = "auto",
				variant = "default", -- default, tinted, deuteranopia, tritanopia
				transparent = false,
				dim_inactive = false,
				hide_inactive_statusline = false,
				styles = {
					comments = {},
					keywords = { bold = true },
					functions = { bold = true },
					variables = {},
				},
			})
		end,
	},
	{
		"vague2k/vague.nvim",
		lazy = true,
		priority = 1000,
		opts = {
			transparent = false,
			style = {
				boolean = "none",
				number = "none",
				float = "none",
				error = "none",
				comments = "none",
				conditionals = "none",
				functions = "bold",
				headings = "bold",
				operators = "none",
				strings = "none",
				variables = "none",
				keywords = "bold",
				keyword_return = "bold",
				keywords_loop = "bold",
				keywords_label = "none",
				keywords_exception = "bold",
				builtin_constants = "bold",
				builtin_functions = "bold",
				builtin_types = "bold",
				builtin_variables = "none",
			},
		},
	},
	{
		"blazkowolf/gruber-darker.nvim",
		lazy = true,
		priority = 1000,
		opts = {
			bold = true,
			invert = {
				signs = false,
				tabline = false,
				visual = true,
			},
			italic = {
				strings = false,
				comments = false,
				operators = false,
				folds = false,
			},
			undercurl = true,
			underline = true,
		},
	},
	{ "wadackel/vim-dogrun", lazy = true, priority = 1000 },
	{
		"dgox16/oldworld.nvim",
		lazy = true,
		priority = 1000,
		opts = {
			terminal_colors = true,
			styles = {
				comments = {},
				keywords = { bold = true },
				identifiers = { bold = true },
				functions = { bold = true },
				variables = {},
				booleans = { bold = true },
			},
			integrations = {
				alpha = false,
				cmp = true,
				flash = false,
				gitsigns = true,
				hop = false,
				indent_blankline = false,
				lazy = true,
				lsp = true,
				markdown = true,
				mason = true,
				navic = false,
				neo_tree = false,
				neorg = false,
				noice = false,
				notify = true,
				rainbow_delimiters = true,
				telescope = true,
				treesitter = true,
			},
		},
	},
	{
		"oxfist/night-owl.nvim",
		lazy = true,
		priority = 1000,
		opts = {
			bold = true,
			italics = false,
			underline = true,
			undercurl = true,
			transparent_background = false,
		},
	},
	{
		"mellow-theme/mellow.nvim",
		lazy = true,
		priority = 1000,
		config = function()
			vim.g.mellow_italic_comments = false
			vim.g.mellow_italic_keywords = false
			vim.g.mellow_italic_booleans = false
			vim.g.mellow_italic_functions = false
			vim.g.mellow_italic_variables = false
			vim.g.mellow_bold_comments = false
			vim.g.mellow_bold_keywords = true
			vim.g.mellow_bold_booleans = true
			vim.g.mellow_bold_functions = true
			vim.g.mellow_bold_variables = false
			vim.g.mellow_transparent = false
		end,
	},
}
